# Generated by Django 4.0.3 on 2022-03-14 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0002_alter_answercomment_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='content',
            new_name='answer_content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='question_content',
        ),
    ]
