# Generated by Django 4.0.3 on 2022-03-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0003_rename_content_answer_answer_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_content',
            new_name='content',
        ),
    ]
