# Generated by Django 4.0.3 on 2022-03-15 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0005_tag_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='user',
            new_name='owner',
        ),
    ]
